version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m http.server 3001
    
  frontend:
    build:
      context: ./frontend_new
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend_new:/app
      - /app/node_modules
    depends_on:
      - backend
